# Site settings
email: tosinmath007@gmail.com
baseurl: "https://tosinonikute.github.io/"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Tosin O.
description: I build stuff for the web and mobile.
url: "https://tosinonikute.github.io/"
twitter_username: 
default_img: 

# Profile settings
name: Tosin
profile_img: 
profile: 
social:
  github: 

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
permalink: /:year/:month/:day/:title/
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  
#comments
disqus-shortname: tosinmath007

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]


